### ISSUE TITLE
Likes counter for specific url

### ISSUE THREAD

**Issue by delodepote** [goncaloneves/likescounter#1]
Hi, 
is there a way to obtain likes for specific url instead of Facebook page or ID?

Thanks for help

**Comment by goncaloneves** [comment]
Hi delodepote,

If the url you are saying has likes, it is possible.

https://graph.facebook.com/?id=facebook
returns the same as:
https://graph.facebook.com/?id=https://www.facebook.com/facebook

You can write an entire url on the page attribute.

Likes Counter uses Facebook Graph API see: https://developers.facebook.com/docs/graph-api/using-graph-api/
